Repository massenergize/frontend-portal, pull requests merged in 2020-05, with the labels that each got.

#218 Fix "Uncaught Invariant Violation" error
  v2.0/src/Components/Menu/NavBarBurger.js
Labels: bug

#220 Josh events changes & bugfixes
  v2.0/src/Components/Menu/NavBarBurger.js
  v2.0/src/Components/Pages/EventsPage/EventsPageReal.js
  v2.0/src/Components/Pages/EventsPage/OneEventPage.js
  v2.0/src/Components/Pages/HomePage/EventHomepageSection.js
  v2.0/src/components/Utils.js
Labels: bug, enhancement

#225 Welcome images overhaul (resize cropping + carousel)
  v2.0/src/Components/Pages/EventsPage/OneEventPage.js
  v2.0/src/Components/Shared/WelcomeImages.js
  v2.0/src/components/Utils.js
Labels: enhancement

#232 Events page fix
  v2.0/src/Components/Pages/ActionsPage/OneActionPage.js
  v2.0/src/Components/Pages/EventsPage/OneEventPage.js
Labels: bug, enhancement

#237 Merge changes into Master - excluding home page photos
  v2.0/deployment/build.json
  v2.0/package-lock.json
  v2.0/public/index.html
  v2.0/src/AppRouter.js
  v2.0/src/Components/Menu/NavBarBurger.js
  v2.0/src/Components/Pages/ActionsPage/Action.js
  v2.0/src/Components/Pages/ActionsPage/ActionsPage.js
  v2.0/src/Components/Pages/ActionsPage/ChooseHHForm.js
  v2.0/src/Components/Pages/ActionsPage/OneActionPage.js
  v2.0/src/Components/Pages/CommunitySelectPage.js
  v2.0/src/Components/Pages/EventsPage/EventsPageReal.js
  v2.0/src/Components/Pages/EventsPage/OneEventPage.js
  v2.0/src/Components/Pages/EventsPage/oops.png
  v2.0/src/Components/Pages/HomePage/EventHomepageSection.js
  v2.0/src/Components/Pages/HomePage/HomePage.js
  v2.0/src/Components/Pages/ImpactPage/ImpactPage.js
  v2.0/src/Components/Pages/LoginPage/LoginForm.js
  v2.0/src/Components/Pages/ProfilePage/AddingHouseholdForm.js
  v2.0/src/Components/Pages/ProfilePage/ChangeEmailForm.js
  v2.0/src/Components/Pages/ProfilePage/DeleteAccountForm.js
  v2.0/src/Components/Pages/ProfilePage/EditingProfileForm.js
  v2.0/src/Components/Pages/ProfilePage/ProfilePage.js
  v2.0/src/Components/Pages/RegisterPage/RegisterForm.js
  v2.0/src/Components/Pages/RegisterPage/RegisterPage.js
  v2.0/src/Components/Pages/ServicesPage/OneServicePage.js
  v2.0/src/Components/Pages/TeamsPage/TeamsPage.js
  v2.0/src/Components/Pages/TeamsPage/teams_pop.jpg
  v2.0/src/Components/Shared/BarGraph.js
  v2.0/src/Components/Shared/CircleGraph.js
  v2.0/src/assets/css/extras.css
  v2.0/src/components/Utils.js
  v2.0/src/config/config.json
Labels: Priority 1
