Repository massenergize/frontend-portal, pull requests merged in 2020-06, with the labels that each got.

#247 Merge Dev changes into Master
  .gitignore
  .vscode/settings.json
  v2.0/deployment/build.json
  v2.0/package-lock.json
  v2.0/public/index.html
  v2.0/src/AppRouter.js
  v2.0/src/Components/Menu/NavBarBurger.js
  v2.0/src/Components/Menu/NavBarBurger.js.orig
  v2.0/src/Components/Pages/ActionsPage/Action.js
  v2.0/src/Components/Pages/ActionsPage/ActionsPage.js
  v2.0/src/Components/Pages/ActionsPage/ChooseHHForm.js
  v2.0/src/Components/Pages/ActionsPage/OneActionPage.js
  v2.0/src/Components/Pages/ActionsPage/StoryForm-copy.js
  v2.0/src/Components/Pages/CommunitySelectPage.js
  v2.0/src/Components/Pages/EventsPage/EventsPageReal.js
  v2.0/src/Components/Pages/EventsPage/OneEventPage.js
  v2.0/src/Components/Pages/EventsPage/oops.png
  v2.0/src/Components/Pages/HomePage/EventHomepageSection.js
  v2.0/src/Components/Pages/HomePage/Events copy.js
  v2.0/src/Components/Pages/HomePage/HomePage.js
  v2.0/src/Components/Pages/HomePage/IconBox.js
  v2.0/src/Components/Pages/HomePage/IconBoxTable.js
  v2.0/src/Components/Pages/ImpactPage/ImpactPage.js
  v2.0/src/Components/Pages/LoginPage/LoginForm.js
  v2.0/src/Components/Pages/ProfilePage/AddingHouseholdForm.js
  v2.0/src/Components/Pages/ProfilePage/ChangeEmailForm.js
  v2.0/src/Components/Pages/ProfilePage/DeleteAccountForm.js
  v2.0/src/Components/Pages/ProfilePage/EditingProfileForm.js
  v2.0/src/Components/Pages/ProfilePage/ProfilePage.js
  v2.0/src/Components/Pages/RegisterPage/RegisterForm.js
  v2.0/src/Components/Pages/RegisterPage/RegisterPage.js
  v2.0/src/Components/Pages/ServicesPage/OneServicePage.js
  v2.0/src/Components/Pages/TeamsPage/TeamsPage.js
  v2.0/src/Components/Pages/TeamsPage/teams_pop.jpg
  v2.0/src/Components/Shared/BarGraph.js
  v2.0/src/Components/Shared/CircleGraph.js
  v2.0/src/Components/Shared/WelcomeImages.js
  v2.0/src/assets/css/extras.css
  v2.0/src/assets/css/style.css
  v2.0/src/components/Utils.js
  v2.0/src/config/config.json
Labels: Priority 1

#251 Fix infinite loop in OneActionPage
  v2.0/src/Components/Pages/ActionsPage/OneActionPage.js
Labels: critical

#252 ComponentDidUpdate causing infinite loop?
  v2.0/deployment/build.json
  v2.0/src/Components/Pages/ActionsPage/OneActionPage.js
  v2.0/src/config/config.json
Labels: critical

#259 top bar variable height to accomidate different-sized logos
  v2.0/src/Components/Menu/NavBarBurger.js
  v2.0/src/Components/Pages/HomePage/HomePage.js
  v2.0/src/assets/css/extras.css
  v2.0/src/assets/css/responsive.css
  v2.0/src/assets/css/style.css
Labels: enhancement

#269 Teams redesign phase 1
  v2.0/src/AppRouter.js
  v2.0/src/Components/Pages/TeamsPage/TeamsPage.js
  v2.0/src/assets/css/extras.css
  v2.0/src/assets/css/style.css
  v2.0/src/components/Pages/TeamsPage/CompareTeamsPage.js
  v2.0/src/components/Pages/TeamsPage/ContactAdminModal.js
  v2.0/src/components/Pages/TeamsPage/JoinTeamModal.js
  v2.0/src/components/Pages/TeamsPage/LeaveTeamModal.js
  v2.0/src/components/Pages/TeamsPage/OneTeamPage.js
  v2.0/src/components/Pages/TeamsPage/TeamActionsGraph.js
  v2.0/src/components/Pages/TeamsPage/TeamInfoBars.js
  v2.0/src/components/Pages/TeamsPage/TeamMembersList.js
  v2.0/src/components/Utils.js
Labels: enhancement
