Repository massenergize/frontend-portal, pull requests merged in 2021-11, with the labels that each got.

#748 Issue 628: Story preferred name by default
  src/components/Pages/ActionsPage/StoryForm.js
  src/components/Pages/HomePage/EventHomepageSection.js
  src/components/Pages/ServicesPage/ServicesPage.js
  src/components/Pages/StoriesPage/OneTestimonialPage.js
  src/components/Pages/StoriesPage/StoriesPage.js
  src/components/Pages/StoriesPage/Story Sheet/StorySheet.js
Labels: bug, Priority 1

#751 712 - donuts reverse progress after 100%
  src/components/Utils.js
Labels: bug, priority 2

#762 758 Creating profile on sandbox
  src/components/Pages/RegisterPage/RegisterForm.js
Labels: bug, Priority 1

#766 Dani tour new from dev
  deployment/build.json
  package-lock.json
  package.json
  src/components/Pages/ActionsPage/ActionsPage.js
  src/components/Pages/ActionsPage/OneActionPage.js
  src/components/Pages/HomePage/HomePage.js
  src/components/Pages/ImpactPage/ImpactPage.js
  src/components/Pages/LoginPage/LoginPage.js
  src/components/Pages/RegisterPage/RegisterForm.js
  src/config/config.json
Labels: enhancement, Priority 1

#768 Fixed link second frame of tour
  src/components/Pages/ActionsPage/ActionsPage.js
  src/components/Pages/HomePage/HomePage.js
  src/components/Pages/ImpactPage/ImpactPage.js
Labels: enhancement, Priority 1

#775 Bug fixes for prod
  src/AppRouter.js
  src/api/urls.js
  src/components/Menu/FooterLinks.js
  src/components/Pages/EventsPage/NewEventsCard.js
  src/components/Pages/HomePage/IconBox.js
Labels: Priority 1

#777 Copy changes in most of the frames. Added tour to teams page
  deployment/build.json
  src/components/Pages/AboutUsPage/AboutUsPage.js
  src/components/Pages/ActionsPage/ActionsPage.js
  src/components/Pages/ActionsPage/OneActionPage.js
  src/components/Pages/HomePage/HomePage.js
  src/components/Pages/ImpactPage/ImpactPage.js
  src/components/Pages/RegisterPage/RegisterForm.js
  src/components/Pages/TeamsPage/TeamsPage.js
  src/config/config.json
Labels: enhancement

#780 Control tour with localStorage
  deployment/build.json
  src/components/Pages/ActionsPage/ActionsPage.js
  src/components/Pages/ActionsPage/OneActionPage.js
  src/components/Pages/HomePage/HomePage.js
  src/components/Pages/ImpactPage/ImpactPage.js
  src/components/Pages/RegisterPage/RegisterForm.js
  src/components/Pages/TeamsPage/TeamsPage.js
  src/components/Utils.js
  src/config/config.json
Labels: enhancement
